# AI Reviewer Configuration
# Copy this file to your repository root as .ai-reviewer.yml

# PR Structure Rules
pr_structure:
  # Title must follow conventional commits format
  title_pattern: "^(feat|fix|docs|style|refactor|test|chore|perf|ci|build|revert)(\\(.+\\))?!?:.+"
  
  # Require a description for all PRs
  require_description: true
  min_description_length: 20
  
  # Require linked issues (set to true for stricter projects)
  require_linked_issue: false
  
  # Require screenshots for UI changes
  require_screenshot_for:
    - "*.css"
    - "*.scss"
    - "*.html"
    - "*.jsx"
    - "*.tsx"
    - "*.vue"
    - "*.svelte"

# PR Size Limits
pr_size:
  max_files: 20
  max_lines_added: 500
  max_lines_deleted: 300
  warning_threshold: 0.7  # Warn at 70% of limit

# Files/patterns to ignore during review
ignore:
  - "*.lock"
  - "*.min.js"
  - "*.min.css"
  - "*.map"
  - "package-lock.json"
  - "yarn.lock"
  - "pnpm-lock.yaml"
  - "poetry.lock"
  - "Pipfile.lock"
  - "dist/*"
  - "build/*"
  - "node_modules/*"
  - ".git/*"
  - "*.generated.*"
  - "*.auto.*"

# Test Requirements
testing:
  # Source files that should have tests
  require_tests_for:
    - "src/**/*.py"
    - "src/**/*.js"
    - "src/**/*.ts"
    - "lib/**/*.py"
    - "app/**/*.py"
  
  # Patterns to identify test files
  test_file_patterns:
    - "test_*.py"
    - "*_test.py"
    - "tests/**/*.py"
    - "*.test.js"
    - "*.spec.js"
    - "*.test.ts"
    - "*.spec.ts"
    - "__tests__/**/*"

# Security Patterns (additional custom patterns)
# security:
#   patterns:
#     - name: "Example Pattern"
#       regex: "example"
#       severity: "LOW"
#       description: "Example description"

# Naming Conventions
naming:
  python:
    class: "^[A-Z][a-zA-Z0-9]*$"      # PascalCase
    function: "^[a-z_][a-z0-9_]*$"     # snake_case
    constant: "^[A-Z][A-Z0-9_]*$"      # SCREAMING_SNAKE_CASE
  javascript:
    class: "^[A-Z][a-zA-Z0-9]*$"       # PascalCase
    function: "^[a-z][a-zA-Z0-9]*$"    # camelCase
    constant: "^[A-Z][A-Z0-9_]*$"      # SCREAMING_SNAKE_CASE
