name: 'AI PR Reviewer'
description: 'AI-powered code review for Pull Requests using OpenAI GPT'
author: 'Your Name'

branding:
  icon: 'code'
  color: 'purple'

inputs:
  openai_model:
    description: 'OpenAI model to use'
    required: false
    default: 'gpt-4o-mini'
  max_tokens:
    description: 'Maximum tokens for AI response'
    required: false
    default: '4096'
  review_comment_lgtm:
    description: 'Leave a comment even when code looks good'
    required: false
    default: 'false'
  review_simple_changes:
    description: 'Review even simple changes (false to skip trivial PRs)'
    required: false
    default: 'false'
  debug:
    description: 'Enable debug logging'
    required: false
    default: 'false'
  config_path:
    description: 'Path to custom config file (optional)'
    required: false
    default: '.ai-reviewer.yml'
  enable_storage:
    description: 'Enable MongoDB/Redis storage (v2 feature)'
    required: false
    default: 'false'
  mongodb_uri:
    description: 'MongoDB connection URI'
    required: false
  mongodb_database:
    description: 'MongoDB database name'
    required: false
    default: 'ai_reviewer'
  redis_host:
    description: 'Redis host'
    required: false
  redis_port:
    description: 'Redis port'
    required: false
    default: '6379'
  redis_password:
    description: 'Redis password'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: |
        pip install -q -r ${{ github.action_path }}/requirements-review.txt

    - name: Run AI Reviewer
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_BODY: ${{ github.event.pull_request.body }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        OPENAI_MODEL: ${{ inputs.openai_model }}
        MAX_TOKENS: ${{ inputs.max_tokens }}
        DEBUG: ${{ inputs.debug }}
        REVIEW_COMMENT_LGTM: ${{ inputs.review_comment_lgtm }}
        REVIEW_SIMPLE_CHANGES: ${{ inputs.review_simple_changes }}
        CONFIG_PATH: ${{ inputs.config_path }}
        # Storage Configuration
        ENABLE_STORAGE: ${{ inputs.enable_storage }}
        MONGODB_URI: ${{ inputs.mongodb_uri }}
        MONGODB_DATABASE: ${{ inputs.mongodb_database }}
        REDIS_HOST: ${{ inputs.redis_host }}
        REDIS_PORT: ${{ inputs.redis_port }}
        REDIS_PASSWORD: ${{ inputs.redis_password }}
      run: |
        python ${{ github.action_path }}/ai_reviewer/main.py
